/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#ifndef NODESET_GENERATED_H_
#define NODESET_GENERATED_H_

#ifdef UA_ENABLE_AMALGAMATION
#include "open62541.h"
#else
#include <open62541/types.h>
#include <open62541/types_generated.h>

#endif



_UA_BEGIN_DECLS


/**
 * Every type is assigned an index in an array containing the type descriptions.
 * These descriptions are used during type handling (copying, deletion,
 * binary encoding, ...). */
#define UA_NODESET_COUNT 2
extern UA_EXPORT const UA_DataType UA_NODESET[UA_NODESET_COUNT];

/**
 * IdentifierType
 * ^^^^^^^^^^^^^^
 * Id struct to represent idH and idL of an ov object. */
typedef struct {
    UA_UInt32 idH;
    UA_UInt32 idL;
} UA_IdentifierType;

#define UA_NODESET_IDENTIFIERTYPE 0

/**
 * ActimodeType
 * ^^^^^^^^^^^^
 * Enumeration data type for an actimode of a fb task (c.f. FB_AM_... in fb_namedef.h) */
typedef enum {
    UA_ACTIMODETYPE_OFF = 0,
    UA_ACTIMODETYPE_ON = 1,
    UA_ACTIMODETYPE_UNLINK = 2,
    UA_ACTIMODETYPE_ONCE = 3,
    UA_ACTIMODETYPE_CATCHUP = 10,
    __UA_ACTIMODETYPE_FORCE32BIT = 0x7fffffff
} UA_ActimodeType;
UA_STATIC_ASSERT(sizeof(UA_ActimodeType) == sizeof(UA_Int32), enum_must_be_32bit);

#define UA_NODESET_ACTIMODETYPE 1


_UA_END_DECLS

#endif /* NODESET_GENERATED_H_ */
