/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#ifndef UA_NODEIDS_NS2_H_
#define UA_NODEIDS_NS2_H_

/**
 * Namespace Zero NodeIds
 * ----------------------
 * Numeric identifiers of standard-defined nodes in namespace zero. The
 * following definitions are autogenerated from a CSV file */

#define UA_NS2ID_FUNCTIONCHART 1 /* ObjectType */
#define UA_NS2ID_ACTIMODETYPE 2 /* DataType */
#define UA_NS2ID_IDENTIFIERTYPE 3 /* DataType */
#define UA_NS2ID_IDENTIFIERTYPE_ENCODING_DEFAULTBINARY 4 /* Object */
#define UA_NS2ID_IDENTIFIERTYPE_ENCODING_DEFAULTXML 5 /* Object */
#define UA_NS2ID_ACTIMODETYPE_ENUMVALUES 8 /* Variable */
#define UA_NS2ID_FUNCTIONCHART_ID 15 /* Variable */
#define UA_NS2ID_FUNCTIONCHART_ACTIMODE 16 /* Variable */
#endif /* UA_NODEIDS_NS2_H_ */ 
